version: '2'
services:
  web:
    build: .
    # volumes:
    #   - .:/app
    ports:
      - "8888:8888"
    # network_mode: host
    # environment:
    #   - FLASK_APP=main.py
    #   - FLASK_DEBUG=1
    #   - 'RUN=flask run --host=0.0.0.0 --port=5000'